import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Stripe from 'stripe';
import { checkout } from 'checkout';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const item_1 = {
    id: 'price_1MWpyVJ3g5muo4H8KhPeAeYa',
    title: '30 days plan',
  };
  const item_2 = {
    id: 'price_1MWpxgJ3g5muo4H8PTx0JSMf',
    title: '14 days plan',
  };
  const item_3 = {
    id: 'price_1MWpwEJ3g5muo4H8nd7VsPpv',
    title: '7 days plan',
  };
  var items = [item_1, item_2, item_3];
  const clicked = (item) => {
    checkout({
      lineItems: [
        {
          price: item.id,
          quantity: 1,
        },
      ],
    });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main
        className={styles.main}
        style={{ display: 'block', margin: '0px auto' }}
      >
        {items.map((item) => {
          return (
            <div
              style={{
                minWidth: '200px',
                minHeight: '120px',
                textAlign: 'center',
                backgroundColor: '#f0f0f0',
                display: 'block',
                float: 'left',
                marginRight: '10px',
                cursor: 'pointer',
                padding: '40px 0px',
              }}
              key={item.id}
              onClick={() => {
                clicked(item);
              }}
            >
              <span style={{ margin: 'auto auto' }}>{item.title}</span>
            </div>
          );
        })}
      </main>
    </>
  );
}
